### ISSUE TITLE
How to configure authentication to office 365/Azure AD with on-prem AD using PIV (UPN identifier)

### ISSUE THREAD

**Issue by muhammadj517** [GSA/piv-guides#258] opened 2019-11-29 13:43 UTC
#### Description of Issue: ####
How to link Active directory UPN# to Alt secure ID via a logon script or some other method.

#### Details of Issue: ####
the goal is to enable authentication from windows active directory using UPN# to link to Alt security ID

**Comment by maxwellfunk** [comment] 2021-03-22 17:34
We do currently have instructions for AD authentication with both UPN and AltSecIDs at the following page (assuming this is primarily for on-prem directories):
https://piv.idmanagement.gov/networkconfig/accounts/

Assume you would like guidance integrating cloud directories with on-prem.  Cloud identity infrastructure is a potential topic for a future playbook.

**Comment by maxwellfunk** [comment] 2021-03-22 19:33
essentially a duplicate of issue #58

**Comment by maxwellfunk** [comment] 2021-03-22 19:34
closing after referenced in #58

**Closed as completed** 2021-03-22 19:34 UTC
Labels: duplicate, Migrate
